# -*- coding: utf-8 -*-
"""soil analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IP1ofBv0tmXfFX35U55CW64836zoNhsa
"""

print("Welcome to soil and water analysis for farming recommendations")

import pandas as pd

m=pd.read_csv('/content/soil_moisture.csv')
p=pd.read_csv('/content/Smart_Farming_Crop_Yield_2024.csv')

m.head()

print(m.columns)
print(p.columns)

moist=m[['temperature','humidity','ph','rainfall','soil_moisture']]
moist.head()

phs=p[['humidity_%','temperature_C','rainfall_mm','pesticide_usage_ml','soil_moisture_%','soil_pH',]].rename(columns={"humidity_%":"humidity","temperature_C":"temperature","soil_pH":"ph","rainfall_mm":"rainfall","soil_moisture_%":"soil_moisture"})

phs.head()

final=pd.concat([moist,phs],ignore_index=True)
final.head()

final.head()

final["irrigation_required"] = (
    (100 - final["soil_moisture"]) * 0.3 +
    final["temperature"] * 0.2 -
    final["rainfall"] * 0.05
)

final["irrigation_required"] = final["irrigation_required"].clip(lower=0)

OPTIMAL_PH = 6.5

final["ph_correction_amount"] = abs(final["ph"] - OPTIMAL_PH) * 10

final.head()

X = final[['temperature', 'humidity', 'ph', 'rainfall', 'soil_moisture']]

y = final[['irrigation_required', 'ph_correction_amount']]

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2,random_state=42)
model=RandomForestRegressor(n_estimators=100,random_state=42)
model.fit(xtrain,ytrain)

"""sample = [[
    25.0,   # temperature
    78.0,   # humidity
    6.8,    # current pH
    120.0,  # rainfall
    30.0    # soil moisture
]]

prediction = model.predict(sample)

irrigation, ph_adjust = prediction[0]

print("Irrigation needed (mm):", irrigation)
print("pH correction amount:", ph_adjust)"""


temp=int(input())
hum=int(input())
ph=float(input())
rain=int(input())
soil=int(input())
model.predict([[temp,hum,ph,rain,soil]])
print("Irrigation needed (mm):", irrigation)
print("pH correction amount:", ph_adjust)